models/__init__.py
from models.main import User, Order

models/main.py
from pony.orm import *
from datetime import datetime
database = Database()


class User(database.Entity):
    username = Required(str, unique=True)
    password = Required(str)
    display_name = Required(str)
    admin = Required(bool)

class Order(database.Entity):
    name = Required(str)
    date = Required(datetime)
    data = Required(Json)

# class Estimate(database.Entity):
#     pass

# class Product(database.Entity):
#     pass

# class Section(database.Entity):
#     pass

# class Part(database.Entity):
#     pass

app.py
from flask import Flask, session
from flask.helpers import url_for
from werkzeug.utils import redirect
from blueprints import auth_blueprint, dashboard_blueprint, estimate_api_blueprint
from models.main import User, database
from pony.orm import db_session, select
from flask_cors import CORS


app = Flask(__name__)
CORS(app)
app.register_blueprint(auth_blueprint)
app.register_blueprint(dashboard_blueprint)
app.register_blueprint(estimate_api_blueprint)
app.config["SECRET_KEY"] = "add50c38-0102-4490-83bf-c08f56a8f66a"
app.config['JSON_SORT_KEYS'] = False


@app.before_first_request
def handle_startup():
    # if app.debug == True:
    #     database.bind("sqlite", "database.sqlite", create_db=True)
    # elif app.debug == False:
    #     database.bind(provider='postgres', user='vjxssxtaunspvh', password='b2b8dd9ab9400ca06ad2045cb9fb808b9d077ce6d514474ead7d7d058436ab3e',
    #                   host='ec2-3-228-134-188.compute-1.amazonaws.com', database='d264r6pqscns36')

    database.bind("sqlite", "database.sqlite", create_db=True)
    database.generate_mapping(create_tables=True)
    try:
        with db_session:
            u = User(username="zestadmin", password="zestadmin82008",
                     display_name="administrator", admin=True)
            print(list(select(p for p in User)))
    except Exception as e:
        print(e)


@app.get("/")
def index():
    return redirect(url_for("auth.login_page"))


if __name__ == "__main__":
    app.run(debug=False, port=5000)
    # app.run(host="0.0.0.0")

blueprints/__init__.py
from blueprints.auth import auth_blueprint
from blueprints.dashboard import dashboard_blueprint
from blueprints.estimate import estimate_api_blueprint

blueprints/auth.py
from flask import Blueprint, request, session
from flask.helpers import url_for
from flask.templating import render_template
from werkzeug.utils import redirect
from models.main import User
from pony.orm import db_session

auth_blueprint = Blueprint("auth", __name__, url_prefix="/auth")

credentials = {
    "username": "admin",
    "password": "password"
}


@auth_blueprint.get("/")
def login_page():
    if session.get("user") is not None:
        return redirect(url_for("dashboard.index"))
    return render_template("login.html")


def authenticate(data: dict) -> bool:
    with db_session:
        user = User.get(username=data.get('username'))
        if user is not None and user.password == data.get('password'):
            return user
        return None


@auth_blueprint.post("/login")
def login():
    form_data = request.form.to_dict()
    user = authenticate(form_data)
    if user is not None:
        user_data = user.to_dict()
        user_data.pop("password")
        session["user"] = user_data
        return redirect(url_for("dashboard.index"))
    else:
        return redirect(url_for("index"))


@auth_blueprint.get("/logout")
def logout():
    session.pop("user")
    return redirect(url_for("index"))

blueprints/dashboard.py
from flask import Blueprint, session, render_template, request
from flask.helpers import url_for
from werkzeug.utils import redirect
from pony.orm import *
from models import Order
import calendar

dashboard_blueprint = Blueprint("dashboard", __name__, url_prefix="/dashboard")


@dashboard_blueprint.before_request
def before_request_func():
    if session.get("user") is None:
        return redirect(url_for("index"))


@dashboard_blueprint.get("/")
def index():
    return render_template("home.html")


@dashboard_blueprint.get("/estimate")
def estimate():
    return render_template("estimate.html")


@dashboard_blueprint.get("/types")
def types_of_window():
    return render_template("types.html")


@dashboard_blueprint.get("/order")
def order():
    order_id = request.args.get("id")
    with db_session:
        order = Order.get(id=order_id)
        return render_template("order.html", order=order)


@dashboard_blueprint.get("/all_orders")
def all_orders():
    with db_session:
        orders = select(o for o in Order).order_by(lambda o: o.date)
        print(list(orders))
        months = {}
        for i in orders:
            if i.date.strftime("%B %Y") not in months.keys():
                months[i.date.strftime("%B %Y")] = []
            months[i.date.strftime("%B %Y")].append(i)
        print(months)
        return render_template("all_orders.html", months=months)


@dashboard_blueprint.get("/profile")
def profile():
    return render_template("profile.html")


@dashboard_blueprint.get("/delete")
def delete_order():
    id = request.args.get("id")
    with db_session:
        order = Order.get(id=id)
        order.delete()
        return redirect(url_for("dashboard.all_orders"))


@dashboard_blueprint.get("/month_orders")
def month_orders():
    return render_template("monthly_audit.html")

blueprints/estimate.py
from datetime import datetime
from flask import Blueprint, request
from flask.json import jsonify
from compute import compute_material_required
from pony.orm import *
from models import User
import json
import pytz
from models.main import Order



estimate_api_blueprint = Blueprint(
    "estimate", __name__, url_prefix="/estimate")
IST = pytz.timezone('Asia/Kolkata')


@estimate_api_blueprint.get("/")
def estimate():
    width = request.args.get("width")
    height = request.args.get("height")
    return jsonify(compute_material_required(width=float(width), height=float(height)))


@estimate_api_blueprint.post("/create_order")
def create_order():
    request_data = json.loads(request.data.decode('utf8').replace("'", '"'))
    print(request_data)
    order_name = request_data.get("name")
    username = request_data.get("username")
    password = request_data.get("password")
    order_data = request_data.get("order_data")
    with db_session:
        user = User.get(username=username, password=password)
        if user is not None:
            order = Order(name=order_name,
                          date=datetime.now(IST), data=order_data)
            return jsonify({
                "message": "ok",
                "order_data": order.to_dict()
            })
        return jsonify({
            "message": "error"
        })


def month_string_to_number(string):
    m = {
        'jan': 1,
        'feb': 2,
        'mar': 3,
        'apr': 4,
        'may': 5,
        'jun': 6,
        'jul': 7,
        'aug': 8,
        'sep': 9,
        'oct': 10,
        'nov': 11,
        'dec': 12
    }
    s = string.strip()[:3].lower()
    try:
        out = m[s]
        return out
    except:
        raise ValueError('Not a month')


@estimate_api_blueprint.post("/month_orders")
def month_orders():
    month = request.args.get("month")
    year = request.args.get("year")
    with db_session:
        orders = select(o for o in Order if o.date.month ==
                        month_string_to_number(month) and o.date.year == int(year)).order_by(lambda o: o.date)
        order_dict = {}
        order_dict["orders"] = []
        for i in orders:
            order_dict["orders"].append(i.to_dict())
        return order_dict

templates/all_orders.html
{% extends "dashboard_base.html" %}

{% block content %}

<h1 style="font-weight: lighter;">Monthly Details</h1><hr>

<div class="accordion" id="accordionExample">
  {% for month in months %}
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingTwo">
      <button class="accordion-button collapsed" type="button" data-mdb-toggle="collapse"
        data-mdb-target="#{{ month.split(' ')[0] }}{{ month.split(' ')[1] }}" aria-expanded="false"
        aria-controls="collapseTwo">
        {{month}}
      </button>
    </h2>
    <div id="{{ month.split(' ')[0] }}{{ month.split(' ')[1] }}" class="accordion-collapse collapse"
      aria-labelledby="headingTwo" data-mdb-parent="#accordionExample">
      <div class="accordion-body">
        <a href="{{ url_for('dashboard.month_orders') }}?month={{ month.split(' ')[0] }}&year={{ month.split(' ')[1] }}" class="btn btn-primary">Print Monthly Audit for {{ month.split(' ')[0] }} {{ month.split(' ')[1] }}</a>
        <br><br>
        <table class="table table-bordered table-hover">
          <thead>
            <th scope="col">Name</th>
            <th scope="col">Date</th>
            <th scope="col">Delete</th>
          </thead>
          <tbody>
            {% for i in months[month] %}
            <tr>
              <td><a href="{{ url_for('dashboard.order') }}?id={{i.id}}">{{ i.name }}</a></td>
              <td>{{ i.date }}</td>
              <td><a href="{{ url_for('dashboard.delete_order') }}?id={{ i.id }}" class="btn btn-danger btn-sm">Delete</a></td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <script></script>
  {% endfor %}
</div>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet" />
  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />
  <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.css" rel="stylesheet" />
  <link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}">
  {% block title %}
  {% endblock %}
</head>

<body>
  {% block content %}
  {% endblock %}

</body>
<script
  type="text/javascript"
  src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.js"
></script>

</html>

templates/dashboard_base.html
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet" />
  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />
  <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.css" rel="stylesheet" />
  <link rel="stylesheet" href="{{ url_for('static', filename='dashboard.css') }}">
  {% block title %}
  {% endblock %}
</head>

<body>
  {% include "navbar.html" %}
  <!--Main layout-->
<main style="margin-top: 58px">
  <div class="container pt-4">
    {% block content %}
    {% endblock %}
  
  </div>
</main>
<!--Main layout-->

</body>
<script
  type="text/javascript"
  src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.js"
></script>
{% block scripts %}
{% endblock %}
</html>

templates/estimate.html
{% extends "dashboard_base.html" %}
{% block content %}
<h1 style="font-weight: lighter;">Estimate</h1><hr>
<form  id="estimate_form">
  <div class="form-outline mb-4">
    <input type="number" id="form4Example1" class="form-control"  name="height" />
    <label class="form-label" for="form4Example1">Height</label>
  </div>

  <div class="form-outline mb-4">
    <input type="number" id="form4Example2" class="form-control"  name="width" />
    <label class="form-label" for="form4Example2">Width</label>
  </div>
  <button type = "submit" class="btn btn-primary btn-block mb-4">estimate</button>
</form>

<form id="order-form" style="display: none;">
  <br>
  <div class="form-outline mb-4">
    <input type="text" id="form4Example2" class="form-control"  name="name" />
    <label class="form-label" for="form4Example2">Order Name</label>
  </div>
  <div class="form-outline mb-4">
    <input type="text" id="form4Example2" class="form-control"  name="username" />
    <label class="form-label" for="form4Example2">Re-Enter Username</label>
  </div>
  <div class="form-outline mb-4">
    <input type="password" id="form4Example2" class="form-control"  name="password" />
    <label class="form-label" for="form4Example2">Re-Enter Password</label>
  </div>
  <button class="btn btn-primary" type="submit" id="confirm-order-btn">Confirm Order</button>
</form>

<div class="data-table" id="data-table">
  
</div>
<button class="btn btn-primary" style="display: none;" id="print-btn">Print</button>
{% endblock %}
{% block scripts %}
<script src="{{ url_for('static', filename='main.js') }}"></script>
{% endblock %}

templates/home.html
{% extends "dashboard_base.html" %}

{% block content %}
<h1 style="font-weight: lighter">Products:</h1><hr>
<br>
<div class="row row-cols-1 row-cols-md-3 g-4">
  <div class="col">
    <div class="card">
      <img
        src="https://www.aiswindows.com/wp-content/uploads/2021/01/shutterstock_788319139.jpg"
        class="card-img-top"
        alt="..."
      />
      <div class="card-body">
        <h5 class="card-title">Windows</h5>
        <p class="card-text">
          <a href="{{ url_for('dashboard.types_of_window') }}" class="btn btn-primary btn-block">Select</a>
        </p>
      </div>
    </div>
  </div>
  <!-- <div class="col">
    <div class="card">
      <img
        src="https://mdbootstrap.com/img/new/standard/city/042.jpg"
        class="card-img-top"
        alt="..."
      />
      <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">
          <a href="#" class="btn btn-primary btn-block">View</a>
        </p>
      </div>
    </div>
  </div>
 -->
</div>
{% endblock  %}

templates/login.html
{% extends "base.html" %}
{% block title %}
<title>zest login</title>
{% endblock %}
{% block content %}
<div class="login-form">
  <div class="container">
    <form action="{{ url_for('auth.login') }}" method="post" name="login">
      <img src="{{ url_for('static', filename='winda.svg') }}" class="winda">
      <h1 class="fw-light zest-login-banner">Zest Login</h1><br>
      <input type="text" required class="form-control" placeholder="Username" name="username" autofocus>
      <br>
      <input type="password" required  class="form-control" placeholder="Password" name="password">
      <br>
      <input type="submit" value="Login" class="btn btn-primary submit-btn">
    </form>
  </div>
</div>

{% endblock %}

templates/monthly_audit.html
{% extends "dashboard_base.html" %}
{% block content %}
<button class="btn btn-primary" id="print-btn">Print Monthly Audit</button>
<div id="data-table">

</div>
<script src="{{ url_for('static', filename='main.js') }}"></script>

<script>
  let url = new URL(window.location)
  let month = url.searchParams.get("month")
  let year = url.searchParams.get("year")
  fetch(`/estimate/month_orders?month=${month}&year=${year}`, { "method": "POST" }).then(response => response.json()).then(data => {
    data.orders.forEach(element => {
      document.getElementById("data-table").innerHTML += `<br><br><br><br><div style="border-bottom: 1px solid black"><h3>Order Details:</h3><br>Name: ${element.name}<br>Date: ${element.date.replace("GMT", "IST")} <br>${getTable(element.data)}</div`
    })
  })
  document.getElementById("print-btn").addEventListener("click", (e) => {
    let divContents = document.getElementById("data-table").innerHTML;
    let printWindow = window.open();
    printWindow.document.write(divContents);
    printWindow.document.close();
    printWindow.print();
  });
</script>
{% endblock %}

templates/navbar.html
<!--Main Navigation-->
<header>
  <!-- Sidebar -->
  <nav
       id="sidebarMenu"
       class="collapse d-lg-block sidebar collapse bg-white"
       style="border-bottom: 1px solid black !important;"
       
       >
    <div class="position-sticky">
      <div class="list-group list-group-flush mx-3 mt-4">
        <a
           href="{{ url_for('index') }}"
           class="list-group-item list-group-item-action py-2 ripple"
           aria-current="true"
           >
          <i class="fas fa-tachometer-alt fa-fw me-3"></i
            ><span>Dashboard</span>
        </a>
        <a
           href="{{ url_for('dashboard.all_orders') }}"
           class="list-group-item list-group-item-action py-2 ripple"
           >
          <i class="fas fa-chart-area fa-fw me-3"></i
            ><span>Orders</span>
        </a>
        <a
           href="{{ url_for('dashboard.profile') }}"
           class="list-group-item list-group-item-action py-2 ripple"
           ><i class="fas fa-lock fa-fw me-3"></i><span>Profile</span></a
          >

        <a
           href="{{ url_for('auth.logout') }}"
           class="list-group-item list-group-item-action py-2 ripple"
           ><i class="fas fas fa-sign-out-alt fa-fw me-3"></i
          ><span>Logout</span></a
          >
      </div>
    </div>
  </nav>
  <!-- Sidebar -->

  <!-- Navbar -->
  <nav
       id="main-navbar"
       class="navbar navbar-expand-lg navbar-light bg-white fixed-top"
       >
    <!-- Container wrapper -->
    <div class="container-fluid">
      <!-- Toggle button -->
      <button
              class="navbar-toggler"
              type="button"
              data-mdb-toggle="collapse"
              data-mdb-target="#sidebarMenu"
              aria-controls="sidebarMenu"
              aria-expanded="false"
              aria-label="Toggle navigation"
              >
        <i class="fas fa-bars"></i>
      </button>

      <!-- Brand -->
      <a class="navbar-brand" href="{{ url_for('index') }}">
        Z E S T
      </a>
    <!-- Container wrapper -->
  </nav>
  <!-- Navbar -->
</header>
<!--Main Navigation-->

templates/order.html
{% extends "dashboard_base.html" %}

{% block content %}
<div id="order">
  <h3>Order Info:</h3>
  <b>Name:</b> {{ order.name }}
  <br>
  <b>Date:</b> {{ order.date.strftime('%A %d %B %Y') }}
  <div id="data-table">

  </div>
</div>
<button class="btn btn-primary" id="print-btn">Print Order</button>

<script src="{{ url_for('static', filename='main.js') }}"></script>
<script>
  let height = "{{ order.data['Track - Vertical']['per_piece'] }}"
  let width = "{{ order.data['Track - Top/Bottom']['per_piece'] }}"
  let api_call_url = `/estimate?width=${width}&height=${height}`;
  document.getElementById("data-table").innerHTML = "Loading Audit..."
  fetch(api_call_url)
    .then((response) => {
      return response.json();
    }).then(data => {
      document.getElementById("data-table").innerHTML = getTable(data)
    })
  document.getElementById("print-btn").addEventListener("click", (e) => {
    let divContents = document.getElementById("order").innerHTML;
    let printWindow = window.open();
    printWindow.document.write(divContents);
    printWindow.document.close();
    printWindow.print();
  })
</script>
{% endblock %}

templates/profile.html
{% extends "dashboard_base.html" %}
{% block content %}
<h4>Username:</h4><span>{{ session["user"]["username"] }}</span>
<h4>Display Name:</h4><span>{{ session["user"]["display_name"] }}</span>
<br><br>
<a href="#">Change Password</a>
{% endblock %}

templates/types.html
{% extends "dashboard_base.html" %}

{% block content %}
<div class="row row-cols-1 row-cols-md-3 g-4">
  <div class="col">
    <div class="card">
      <img
        src="https://3.imimg.com/data3/BB/KR/MY-7685255/powder-coated-aluminium-window-500x500.jpg"
        class="card-img-top"
        alt="..."
      />
      <div class="card-body">
        <h5 class="card-title">EURO Series 
          ( 2 + 1 )</h5>
        <p class="card-text">
          <a href="{{ url_for('dashboard.estimate') }}" class="btn btn-primary btn-block">Select</a>
        </p>
      </div>
    </div>
  </div>
</div>
{% endblock  %}